name: Pipeline Workflow

on:
  push:
    branches:
      - dev-001-fiap
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-ci-pipeline-workflow:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev-001-fiap' || github.event_name == 'pull_request' && github.base_ref }}
    uses: tshadz-fiap-postech-soat3/ci-pipeline/.github/workflows/ci-pipeline.yml@dev-fiap-001
    secrets: inherit

  trigger-plan-database-deployment:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: tshadz-fiap-postech-soat3/terraform-database/.github/workflows/terraform-plan-pipeline-ci.yml@main
    secrets: inherit

  trigger-apply-database-deployment:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: trigger-plan-database-deployment
    uses: tshadz-fiap-postech-soat3/terraform-database/.github/workflows/terraform-apply-pipeline-ci.yml@main
    secrets: inherit